name: CI

on:
  push:
    branches: 
        - develop
        - _a_definir_
    

jobs:
  ci:
    name: Continuos Integration
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: gradle
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
          channel: 'stable'
          cache: true
      
      - name: Delete depedencies
        run: flutter clean
        
      - name: Get Dependencies
        run: flutter pub get
        
      - name: Flutter tests
        run: flutter test
        
    
        
  
      
      